In [3]:
import pandas as pd

filepath = "../data/dataset.xlsx"

dataframe = pd.read_excel(filepath)

#dataframe.head()

In [23]:
# Initial data checks
dataframe.shape # Shows the data type for each column (feature)

hasNullValues = dataframe.isnull().sum() # Checks for NaN or None, but NOT " "
#print(hasNullValues)

hasDuplications = dataframe.duplicated().sum() # Checks for duplicate rows
#print(f"Dataframe has: {hasDuplications} duplications")

dataframe.dtypes

statistics = dataframe.describe(include="all") # Prints typical statistical values such as mean, std, count (# of rows)
display(statistics)

,Gallstone Status,Age,Gender,Comorbidity,Coronary Artery Disease (CAD),Hypothyroidism,Hyperlipidemia,Diabetes Mellitus (DM),Height,Weight,Body Mass Index (BMI),Total Body Water (TBW),Extracellular Water (ECW),Intracellular Water (ICW),Extracellular Fluid/Total Body Water (ECF/TBW),Total Body Fat Ratio (TBFR) (%),Lean Mass (LM) (%),Body Protein Content (Protein) (%),Visceral Fat Rating (VFR),Bone Mass (BM),Muscle Mass (MM),Obesity (%),Total Fat Content (TFC),Visceral Fat Area (VFA),Visceral Muscle Area (VMA) (Kg),Hepatic Fat Accumulation (HFA),Glucose,Total Cholesterol (TC),Low Density Lipoprotein (LDL),High Density Lipoprotein (HDL),Triglyceride,Aspartat Aminotransferaz (AST),Alanin Aminotransferaz (ALT),Alkaline Phosphatase (ALP),Creatinine,Glomerular Filtration Rate (GFR),C-Reactive Protein (CRP),Hemoglobin (HGB),Vitamin D
count,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.00000,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000
mean,0.495298,48.068966,0.492163,0.335423,0.037618,0.028213,0.025078,0.134796,167.15674,80.564890,28.877116,40.587774,17.071160,23.634483,42.212038,28.274984,71.638245,15.938809,9.078370,2.803292,54.273041,35.850125,23.487774,12.171599,30.403448,1.150470,108.688715,203.495298,126.652351,49.475549,144.502163,21.684953,26.855799,73.112539,0.800611,100.818903,1.853856,14.418182,21.401411
std,0.500763,12.114558,0.500724,0.517340,0.190568,0.165841,0.156609,0.342042,10.05303,15.709069,5.313707,7.930235,3.161857,5.349332,3.244470,8.444417,8.437598,2.334744,4.332501,0.509467,10.603833,109.799718,9.607607,5.262178,4.460530,1.059217,44.848714,45.758501,38.541175,17.718701,97.904493,16.697605,27.884413,24.181069,0.176433,16.971396,4.989591,1.775815,9.981659
min,0.000000,20.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,145.00000,42.900000,17.400000,13.000000,9.000000,13.800000,29.230000,6.300000,48.990000,5.560000,1.000000,1.400000,4.700000,0.400000,3.100000,0.900000,18.900000,0.000000,69.000000,60.000000,11.000000,25.000000,1.390000,8.000000,3.000000,7.000000,0.460000,10.600000,0.000000,8.500000,3.500000
25%,0.000000,38.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,159.50000,69.600000,25.250000,34.200000,14.800000,19.300000,40.075000,22.025000,65.165000,14.465000,6.000000,2.400000,45.800000,13.900000,17.000000,8.570000,27.250000,0.000000,92.000000,172.000000,100.500000,40.000000,83.000000,15.000000,14.250000,58.000000,0.650000,94.170000,0.000000,13.300000,13.250000
50%,0.000000,49.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,168.00000,78.800000,28.300000,39.800000,17.100000,23.000000,42.000000,27.820000,72.110000,15.870000,9.000000,2.800000,53.900000,25.600000,22.600000,11.590000,30.408108,1.000000,98.000000,198.000000,122.000000,46.500000,119.000000,18.000000,19.000000,71.000000,0.790000,104.000000,0.215000,14.400000,22.000000
75%,1.000000,56.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,175.00000,91.250000,31.850000,47.000000,19.400000,27.550000,44.000000,34.810000,77.850000,17.430000,12.000000,3.200000,62.600000,41.750000,28.550000,15.100000,33.800000,2.000000,109.000000,233.000000,151.000000,56.000000,172.000000,23.000000,30.000000,86.000000,0.920000,110.745000,1.615000,15.700000,28.060000
max,1.000000,96.000000,1.000000,3.000000,1.000000,1.000000,1.000000,1.000000,191.00000,143.500000,49.700000,66.200000,27.800000,57.100000,52.000000,50.920000,93.670000,24.810000,31.000000,4.000000,78.800000,1954.000000,62.500000,41.000000,41.100000,4.000000,575.000000,360.000000,293.000000,273.000000,838.000000,195.000000,372.000000,197.000000,1.460000,132.000000,43.400000,18.800000,53.100000

In [ ]:
# FEATURES THAT SEEM OK BASED ON COMMON SENSE - without a medical degree!
# Gallstone status, age, gender, CAD, Hypothyroidism, Hyperlipidemia ,Diabetes Mellitus (DM)
# Height, Weight,Body Mass Index (BMI),	Total Body Water, Extracellular Water (ECW)
# Intracellular Water (ICW), Extracellular Fluid/Total Body Water (ECF/TBW)
# Total Body Fat Ratio (TBFR) (%), Lean Mass (LM) (%), Body Protein Content (Protein) (%)
# Visceral Fat Rating (VFR), Bone Mass (BM), Muscle Mass (MM, Visceral Fat Area (VFA)
# Visceral Muscle Area (VMA) (Kg), Hepatic Fat Accumulation (HFA)

In [ ]:
# Comorbidity is explained in the docs:  Comorbidity: 0 (No comorbidities present),1 (One comorbid condition), 2 (Two comorbid conditions), 3 (Three or more comorbid conditions)

In [27]:

# DATA THAT SEEM A BIT SUSPICIOUS AT FIRST GLANCE
# Comorbidity is a binary 0 / 1 according to the intro paper
# Obesity (%) 
# Very high max: Glucose,  Low Density Lipoprotein (LDL
# Total Cholesterol (TC), High Density Lipoprotein (HDL)
# Triglyceride, Aspartat Aminotransferaz (AST)
# Alanin Aminotransferaz (ALT), Alkaline Phosphatase (ALP)
# C-Reactive Protein (CRP)

features = [
    'Obesity (%)',
    'Glucose',
    'Low Density Lipoprotein (LDL)',
    'Total Fat Content (TFC)',
    'High Density Lipoprotein (HDL)',
    'Triglyceride',
    'Aspartat Aminotransferaz (AST)',
    'Alanin Aminotransferaz (ALT)',
    'Alkaline Phosphatase (ALP)',
    'C-Reactive Protein (CRP)'
]

dataframe[features].describe(percentiles=[0.25, 0.5, 0.75, 0.95, 0.99]).T

,count,mean,std,min,25%,50%,75%,95%,99%,max
Obesity (%),319.0,35.850125,109.799718,0.40,13.90,25.600,41.750,72.060,96.4518,1954.0
Glucose,319.0,108.688715,44.848714,69.00,92.00,98.000,109.000,168.000,317.6200,575.0
Low Density Lipoprotein (LDL),319.0,126.652351,38.541175,11.00,100.50,122.000,151.000,194.000,223.4600,293.0
Total Fat Content (TFC),319.0,23.487774,9.607607,3.10,17.00,22.600,28.550,40.640,50.3280,62.5
High Density Lipoprotein (HDL),319.0,49.475549,17.718701,25.00,40.00,46.500,56.000,73.000,85.2800,273.0
Triglyceride,319.0,144.502163,97.904493,1.39,83.00,119.000,172.000,316.400,462.3800,838.0
Aspartat Aminotransferaz (AST),319.0,21.684953,16.697605,8.00,15.00,18.000,23.000,39.100,66.5600,195.0
Alanin Aminotransferaz (ALT),319.0,26.855799,27.884413,3.00,14.25,19.000,30.000,64.000,102.8200,372.0
Alkaline Phosphatase (ALP),319.0,73.112539,24.181069,7.00,58.00,71.000,86.000,115.000,143.2000,197.0
C-Reactive Protein (CRP),319.0,1.853856,4.989591,0.00,0.00,0.215,1.615,7.047,29.8300,43.4

In [29]:
dataframe.loc[dataframe['Comorbidity'] > 1.0]

,Gallstone Status,Age,Gender,Comorbidity,Coronary Artery Disease (CAD),Hypothyroidism,Hyperlipidemia,Diabetes Mellitus (DM),Height,Weight,Body Mass Index (BMI),Total Body Water (TBW),Extracellular Water (ECW),Intracellular Water (ICW),Extracellular Fluid/Total Body Water (ECF/TBW),Total Body Fat Ratio (TBFR) (%),Lean Mass (LM) (%),Body Protein Content (Protein) (%),Visceral Fat Rating (VFR),Bone Mass (BM),Muscle Mass (MM),Obesity (%),Total Fat Content (TFC),Visceral Fat Area (VFA),Visceral Muscle Area (VMA) (Kg),Hepatic Fat Accumulation (HFA),Glucose,Total Cholesterol (TC),Low Density Lipoprotein (LDL),High Density Lipoprotein (HDL),Triglyceride,Aspartat Aminotransferaz (AST),Alanin Aminotransferaz (ALT),Alkaline Phosphatase (ALP),Creatinine,Glomerular Filtration Rate (GFR),C-Reactive Protein (CRP),Hemoglobin (HGB),Vitamin D
14,0,59,0,3,1,0,0,0,176,68.4,22.1,37.4,16.6,20.8,44.0,19.7,80.26,20.61,9,2.8,52.1,0.4,13.5,8.0,30.5,1,96.0,280.0,207.0,38.0,190.0,17.0,18.0,70.0,0.78,102.73,0.26,15.6,41.50
15,0,55,0,2,0,0,0,1,170,87.1,30.1,43.5,19.1,24.4,44.0,28.8,71.18,16.83,15,3.1,58.9,36.9,25.1,15.2,32.2,2,84.0,152.0,102.0,36.0,77.0,15.0,24.0,24.0,0.89,100.58,0.16,16.4,51.40
16,0,49,0,3,1,0,0,0,177,90.3,28.8,51.7,20.6,31.1,40.0,20.7,79.29,16.25,10,3.5,68.1,31.1,18.7,11.6,37.1,1,97.0,174.0,94.0,35.0,249.0,17.0,20.0,47.0,0.99,93.38,1.46,15.5,43.34

In [30]:
dataframe.loc[
    dataframe['Obesity (%)'] > 70,
    ['Obesity (%)', 'Body Mass Index (BMI)',
     'Total Body Fat Ratio (TBFR) (%)',
     'Weight', 'Height']
]

,Obesity (%),Body Mass Index (BMI),Total Body Fat Ratio (TBFR) (%),Weight,Height
23,125.60,49.7,42.30,143.5,170
83,83.10,40.3,49.80,100.5,158
90,80.80,39.7,43.60,104.3,162
95,78.20,39.2,42.00,105.5,164
131,73.90,38.3,38.30,80.5,145
134,76.30,38.8,40.30,105.6,165
151,72.60,38.0,40.80,102.2,164
152,72.00,37.8,38.10,82.9,148
194,70.50,37.5,33.30,116.1,176
200,85.80,40.9,34.20,104.6,160
209,106.30,45.4,46.70,102.1,150
222,79.46,40.4,41.17,100.8,158
239,1954.00,29.3,32.63,65.9,150
246,95.64,47.9,49.68,125.8,162
258,80.82,44.3,46.15,109.2,157
280,96.63,48.2,50.92,108.4,150
293,85.90,40.9,36.90,121.0,172
303,76.70,38.9,40.90,97.0,158

In [31]:
from sklearn.model_selection import train_test_split
# Overfitting occurs when a model learns the training data
# too closely, including noise, rather than general patterns.
#
# Split the dataset into training and testing sets.
# Train the model on the training set.
# Evaluate its performance on previously unseen test data.

# X contains all features except the target
X = dataframe.drop(columns=['Gallstone Status'])

# y contains the target variable
y = dataframe['Gallstone Status']


X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (255, 38)
X_test: (64, 38)
y_train: (255,)
y_test: (64,)

In [ ]:
# At this point, phase 1 (exploratory phase) and phase 2 (train/test split) is done
# Next step is phase 3. Data preprocessing, which includes handling missing values, sup measurements, scaling and encoding
# Phase 4 is training the models with the training data and 
# phase 5 is testing the models with metrics etc